### ISSUE TITLE
chore: provide option to run a node without RLN registration

### ISSUE THREAD

**Issue by NagyZoltanPeter** [waku-org/nwaku-compose#104]
### Background
As with the RLNv2 introduction with 0.30.0 coming change on the used blockchain from sepolia to polygon it may be a the right time to clarify for our volunteers for what type of node operation needs RLN registration.

Common node operators will most probably not deploy applications on waku network, just would like to operate a regular waku-node. This means the node will not publish messages on its own but just needs to verify relayed messages via RLN.

### Details
This issue aims to provide regular operators an option to choose between different kind:
- be able to publish messages to the network (TWN) by their own (by light push or relay via REST)
- participate in the network by relaying messages and providing services (lightpush, filter, store)

This will enhance clarity and ease the support of volunteer operators.
This distinction may also help later incentivization.

### Acceptance criteria
- [ ] provide option to run a nwaku-compose node without the need of RLN registration.
- [ ] proper error message to users in case of wrong usage and clarify steps to handle.
- [ ] sanity checks for version upgrades (identify old keystore / rln_tree) offer ways to fix it

**Comment by fryorcraken** [comment]
While we can provide an option. default path should include RLN registration.
The option to run without RLN can be document in repo, but should not encouraged or widely communicated.

**Comment by NagyZoltanPeter** [comment]
> While we can provide an option. default path should mandate RLN registration. The option to run without RLN can be document in repo, but should not encouraged or widely communicated.

In this case it's better icebox or close this issue and not to create confusion with a not recommended option.
