### ISSUE TITLE
[doc] Reclaim disk space

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/nwaku-compose#128]
Diskspace can be limited on a VPS, here are some tips.
Saving some tips in this issue. This could be moved to the advanced readme as a PR.

### 1. Limit DB size

```
echo "export STORAGE_SIZE=20GB" >> .env
# Needs a restart
sudo docker-compose restart
```

### 2. Clean up docker files

```
# Be sure that your containers **are running**
sudo docker-compose up -d

# Clean docker system files
docker system prune -a

# Delete docker images
docker image prune -a

# Delete docker containers
docker container prune

# Delete docker volumes
docker volume prune
```

### 3. Limit log system size

```
sudo journalctl --vacuum-time=2d
```

**Comment by YAMISHKA02** [comment]
what the issue? I can try to help but not really understand where is the problem

**Comment by fryorcraken** [comment]
> what the issue? I can try to help but not really understand where is the problem

Not an issue per se. Just recording some tips. I could have done a PR to add it to the readme instead. Will do if I have to forward this too often to people.

**Comment by fryorcraken** [comment]
Added to doc
