### ISSUE TITLE
Use a generic image instead of hard-coded version

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku-compose#57]
We should use a "nwaku-compose-latest" image tag to upgrade it on each release and not update the `docker-compose.yml` each time.

The question was raised by @jakubgs . Feel free to add any comment I may miss.

**Comment by jakubgs** [comment]
I don't believe I ever said that. I think an explicit version make sense, it should just be overwriteable.

**Comment by jakubgs** [comment]
Having a moving target is bad. I would be against this. You should use known working versions than try to use moving target that will work or not work depending on when you use the compose.

**Comment by alrevuelta** [comment]
Agree. A "nwaku-compose-latest" is not deterministic. Lets use a hardcoded one but with the possibility of overriding it like [we already have](https://github.com/waku-org/nwaku-compose/blob/master/docker-compose.yml#L34) using `NWAKU_IMAGE`.
