### ISSUE TITLE
feat: support negentropy lib for waku sync

### ISSUE THREAD

**Issue by SionoiS** [waku-org/nwaku-compose#92]
`Whoever will do the update nwaku-compose, has to copy the libnegentropy.so into the appropriate path for this to work. Maybe can have an issue to track this in that repo.`

**Comment by alrevuelta** [comment]
Not sure I get this. All nwaku software is dockerized into a container. Why would we need this?

**Comment by SionoiS** [comment]
> Not sure I get this. All nwaku software is dockerized into a container. Why would we need this?

IDK either maybe @chaitanyaprem can shed some light?

**Comment by chaitanyaprem** [comment]
> > Not sure I get this. All nwaku software is dockerized into a container. Why would we need this?
> 
> IDK either maybe @chaitanyaprem can shed some light?

Ah, I see what you mean...the nwaku docker image is just used in compose. Got confused. 
My bad @SionoiS ..then the socket instructions for neaku need to be updated to include the lib in the image and no change in compose.
